Milestone: Tic Tac Toe Project
flpfar/tictactoe-js pull request #1
Opened 2020-07-03 22:36 UTC by shubhsk88

# Tic Tac Toe Project

This PR address the implementation of the tic tac toe project which is provided as part of the Odin project. This project uses the logic of tic tac toe to play the game.

We used :
- Tailwind CSS
- Font Awesome
- Javascript

2020-07-05 11:17 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @shubhsk88 @flpfar 

Nice UI/UX :smiley_cat: Really original. The game is working like a charm!
However, it's not sufficient to move forward. For that, you need to update your code to satisfy the requirement

1. You must separate the Board data structure to the Board DOM. 

So that, 
- When the user click on the Board DOM cell, you update the Board data structure. And then **render** it.
- You use the Board data structure (array of 9 cells) to check the game status, decide whether or not the game should continue. According to the result Update the Game/Board DOM

By doing think like that you will meet some missed requirements

2. As indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/objects_requirement.png), You should have a `game`, `gameboard` objects

3- There should be a function with the only responsibility of rendering the contents of the gameboard array to the webpage, as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/render_requirement.png),

4- You should have a function that that allows a player to 'mark' a spot on the board, as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/mark_requirement.png)

5- As requested also [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/win_requirement.png), there should be a method(s) to check the game's winning conditions

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-07-05 11:17 UTC, maelfosso commented on game.js
> +  ];
That is not something related to only one player. 
All the player will use it.

You should move it out from there. 
Define a method like `checkWinning` and declare it into as constant in order for it to be used to determine the game status.

2020-07-07 17:09 UTC, fatymahmed approved these changes
## Hi @shubhsk88 @flpfar,
The UI looks good 👏👏
Good job implementing the changes 🎉🎉

## Status: Approved ✔️

2020-07-07 17:12 UTC, fatymahmed commented on index.js
> +          }
[OPTIONAL]
- You can improve this part by implementing another method that takes the letter (`X` or `O`) and position `i` as arguments then marks that specific position on the gameboard.

2020-07-11 04:41 UTC, merged